### ISSUE TITLE
Is it for React Native as well?

### ISSUE THREAD

**Issue by proactive-solutions** [xandeer/vue-circle-choice#2]
Hello,

Thanks a lot for the great library.

Can I use if in React Native project. If yes, can you please provide documentation or help me in the same?

**Comment by xandeer** [comment]
Sorry, it isn't.

But if you want this circle UI, I think this article: https://tympanus.net/codrops/2013/08/09/building-a-circular-navigation-with-css-transforms/ is useful for you.

**Comment by proactive-solutions** [comment]
Thanks a lot for the reply. Please close this issue.
